### ISSUE TITLE
`flow-connector-init` hangs after capture connector process has exited

### ISSUE THREAD

**Issue by psFried** [estuary/flow#1273] opened 2023-11-01 22:09 UTC
This was observed on a production capture, which was wedged waiting for the connector to exit. I exec'd into the connector container and found that the actual connector process (in this case `python`) _had_ exited and was a zombie (waiting to be cleaned up by the parent). Meanwhile, the parent (`flow-connector-init`) was just sitting there sleeping. Presumably there's a deadlock or something in connector-init.

```
bash-5.1# ps
PID   USER     TIME  COMMAND
    1 root      0:53 /flow-connector-init --image-inspect-json-path=/image-inspect.json --port 49092
   16 root      6:51 [python]
   20 root      0:00 bash
   26 root      0:00 ps

bash-5.1# cat /proc/16/status
Name:	python
State:	Z (zombie)
Tgid:	16
Ngid:	0
Pid:	16
PPid:	1
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	0
Groups:	0 1 2 3 4 6 10 11 20 26 27
NStgid:	16
NSpid:	16
NSpgid:	1
NSsid:	1
Threads:	1
SigQ:	1/128412
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000001001000
SigCgt:	0000000000000000
CapInh:	0000000000000000
CapPrm:	00000000a80425fb
CapEff:	00000000a80425fb
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	2
Seccomp_filters:	1
Speculation_Store_Bypass:	thread force mitigated
SpeculationIndirectBranch:	conditional force disabled
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	234316
nonvoluntary_ctxt_switches:	6720

bash-5.1# cat /proc/1/status
Name:	flow-connector-
Umask:	0022
State:	S (sleeping)
Tgid:	1
Ngid:	0
Pid:	1
PPid:	0
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	64
Groups:	0 1 2 3 4 6 10 11 20 26 27
NStgid:	1
NSpid:	1
NSpgid:	1
NSsid:	1
VmPeak:	   35476 kB
VmSize:	   12604 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   17800 kB
VmRSS:	    7628 kB
RssAnon:	    1540 kB
RssFile:	    6088 kB
RssShmem:	       0 kB
VmData:	    4024 kB
VmStk:	     132 kB
VmExe:	    5404 kB
VmLib:	       8 kB
VmPTE:	      68 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
CoreDumping:	0
THP_enabled:	1
Threads:	1
SigQ:	1/128412
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000001000
SigCgt:	0000000000004442
CapInh:	0000000000000000
CapPrm:	00000000a80425fb
CapEff:	00000000a80425fb
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	2
Seccomp_filters:	1
Speculation_Store_Bypass:	thread force mitigated
SpeculationIndirectBranch:	conditional force disabled
Cpus_allowed:	ff
Cpus_allowed_list:	0-7
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	262513
nonvoluntary_ctxt_switches:	15315
```

**Comment by psFried** [comment] 2023-11-01 22:47
Actually, this appears to have been caused by a failure to set the shard status, due to the error message being over the limit for etcd documents.

**Comment by jgraettinger** [comment] 2023-11-02 13:01
Yes closing because this is expected behavior: `flow-connector-init` isn't asked to exit until the shard status is cancelled, which doesn't happen until the shard assignment is removed.

**Closed by jgraettinger** 2023-11-02 13:01 UTC
Labels: bug, data-plane
