### ISSUE TITLE
Airbyte Connectors with OAuth Failing

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#357] opened 2022-02-01 22:44 UTC
It appears that any Airbyte connector which uses OAuth is currently failing.  Steps to reproduce:

1. Run `flowctl discover --image=airbyte/source-hubspot` or `flowctl discover --image=airbyte/source-mailchimp` (both use OAuth)
2. Note that the first step works as expected.  Next fill out the required config.  Ping me if you need login credentials.
3. Note that when you rerun the same command as in (1), above, it will hang forever.
4. This doesn't happen with connectors that don't use OAuth.  Ex. `flowctl discover --image=airbyte/source-facebook-marketing` or `flowctl discover --image=airbyte/source-exchange-rates` again here feel free to let me know if you want to test and need API keys.

Finally note that directly hitting docker container works: `docker run --rm -v "$(pwd)/config.json:/config.json" airbyte/source-mailchimp discover --config=/config.json`

**Comment by psFried** [comment] 2022-03-04 00:19
I've tracked this down to a root cause that the connector is, at least in some cases, attempting to read it's mounted configuration twice (at least). This doesn't work because [`connector.Run` passes these configuration files through a named pipe](https://github.com/estuary/flow/blob/master/go/connector/run.go#L147), which can only be read once. This was done intentionally, to avoid the possibility of another process reading the config files. Looking at the airbyte source, I don't think this is something we can reasonably fix with a PR there.

We could simply go back to using regular files, but that doesn't seem like a good long term solution. I could get it in as a short-term fix, but it isn't really seeming worth it.

A better long term fix would be to have the `connector-proxy` manage these as regular files inside of the container, and AFAIK the plan is already to have `connector-proxy` take over decryption and writing of config files. So it seems like maybe our path forward is to just have the `connector-proxy` manage these as regular files instead of pipes. 

@jixij @jgraettinger does that sound reasonable to y'all?

**Comment by jgraettinger** [comment] 2022-03-04 14:22
👍 make sense. To parrot back:

* The runtime uses pipes for passing config to airbyte connectors for security (so that files with secrets aren't sitting around on the host FS). 
* For $reasons, oauth connectors are attempting to read the config twice.
* We're already planning to have the runtime speak the Flow capture protocol to `connector-proxy`.
  * The Flow protocol doesn't use files and passes config just once through the stream (better security posture).
* Planned `connector-proxy` work already requires that it map that config into airbyte-expected files, to pass to the connector delegate.
* We'll use actual files for this, rather than named pipes, to allow for double-reads of config.
* While not _ideal_, at least the file is contained within the connector container (eventual VM) and we can keep it off of the host FS.

**Comment by psFried** [comment] 2022-03-04 17:23
> +1 make sense. To parrot back:

Yep, I think that's exactly right. So this issue should get resolved with estuary/connectors#102

**Closed** 2022-04-15 10:15 UTC
